# Generated by Django 5.0.14 on 2026-03-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_appointment_id_alter_callrequest_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='costo_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='duracion_sesion',
            field=models.PositiveIntegerField(default=60, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='horario_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='idiomas',
            field=models.CharField(blank=True, help_text='Ej. Español, Inglés', max_length=120),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='modalidad',
            field=models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial'), ('ambos', 'Online y Presencial')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='cedula',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='especialidad',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experiencia_anios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='doctores/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
