# Generated by Django 6.0.2 on 2026-07-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('done', 'Realizada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aceptada'), ('in_progress', 'En curso'), ('rejected', 'Rechazada'), ('done', 'Finalizada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
