# Generated by Django 6.0.2 on 2026-09-30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_mobiletoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="foto",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="foto",
            ),
        ),
    ]
