import { Capacitor } from '@capacitor/core'
import { Preferences } from '@capacitor/preferences'
import { BiometricAuth, AndroidBiometryStrength } from '@aparajita/capacitor-biometric-auth'
import './styles.css'

const state={token:null,user:null,api:null,contacts:[]};
const $=s=>document.querySelector(s);const content=$('#content');
function defaultApi(){
  const productionApi=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
  if(productionApi)return productionApi;
  return Capacitor.isNativePlatform()?'http://10.0.2.2:8000/api/v1':'http://127.0.0.1:8000/api/v1';
}
async function prefGet(key){return (await Preferences.get({key})).value}
async function prefSet(key,value){await Preferences.set({key,value})}
async function prefRemove(key){await Preferences.remove({key})}
async function initConfig(){state.api=(await prefGet('cap_api'))||defaultApi()}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json'};if(state.token)opt.headers.Authorization='Bearer '+state.token;const r=await fetch(state.api+path,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'Error de conexión');return d}
async function saveSession(token,user){state.token=token;state.user=user;await prefSet('cap_token',token);await prefSet('cap_user',JSON.stringify(user))}
function showMain(){ $('#loginScreen').classList.add('hidden');$('#mainScreen').classList.remove('hidden');$('#hello').textContent='Hola, '+(state.user.first_name||state.user.full_name||'');go('home') }
async function login(){try{$('#loginMsg').textContent='';const d=await api('/auth/login/',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});await saveSession(d.token,d.user);showMain()}catch(e){$('#loginMsg').textContent=e.message}}
$('#loginBtn').onclick=login;
$('#forgot').onclick=()=>window.open(state.api.replace('/api/v1','')+'/password-reset/','_blank');
async function biometric(){try{if(!Capacitor.isNativePlatform())throw new Error('La biometría se prueba al instalar la app en Android/iOS.');const info=await BiometricAuth.checkBiometry();if(!info.isAvailable)throw new Error('No hay biometría disponible o configurada en este dispositivo.');const token=await prefGet('cap_token'), rawUser=await prefGet('cap_user');if(!token||!rawUser)throw new Error('Primero inicia sesión con correo y contraseña una vez.');await BiometricAuth.authenticate({reason:'Ingresar a CAP Online',cancelTitle:'Cancelar',allowDeviceCredential:true,iosFallbackTitle:'Usar código',androidTitle:'CAP Online',androidSubtitle:'Confirma tu identidad',androidConfirmationRequired:false,androidBiometryStrength:AndroidBiometryStrength.weak});state.token=token;state.user=JSON.parse(rawUser);await api('/me/');showMain()}catch(e){$('#loginMsg').textContent=e.message||'No se pudo validar biometría.'}}
$('#bioBtn').onclick=biometric;
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function doctorCard(d){return `<div class="card doctor"><div class="avatar">${d.foto?`<img src="${d.foto}" style="width:100%;height:100%;object-fit:cover;border-radius:16px">`:'🩺'}</div><div><b>${d.name}</b><div class="muted">${d.especialidad}</div><span class="pill">${d.modalidad}</span> <span class="pill">${d.experiencia_anios} años</span></div></div>`}
async function go(page){try{if(page==='home'){let a=await api('/appointments/');content.innerHTML=`<div class="card"><b>¿Cómo te sientes hoy?</b><div class="moods"><span>😊</span><span>😌</span><span>😐</span><span>😔</span><span>😣</span></div></div><h3 class="section-title">Próxima cita</h3>${a.appointments.length?apptCard(a.appointments.find(x=>['pending','approved'].includes(x.status))||a.appointments[0]):'<div class="card muted">Aún no tienes citas.</div>'}<h3 class="section-title">Accesos rápidos</h3><div class="quick"><button id="qDoctors"><b>♡</b>Psicólogos</button><button id="qApps"><b>▣</b>Mis citas</button><button id="qChat"><b>◯</b>Chat</button><button id="qProfile"><b>☺</b>Perfil</button></div>`;$('#qDoctors').onclick=()=>go('doctors');$('#qApps').onclick=()=>go('appointments');$('#qChat').onclick=()=>go('chat');$('#qProfile').onclick=()=>go('profile')}
else if(page==='doctors'){let d=await api('/doctors/');content.innerHTML=`<input class="search" id="docSearch" placeholder="Buscar especialista..."><div id="docList">${d.doctors.map(doctorCard).join('')}</div>`;$('#docSearch').oninput=async e=>{let x=await api('/doctors/?q='+encodeURIComponent(e.target.value));$('#docList').innerHTML=x.doctors.map(doctorCard).join('')}}
else if(page==='appointments'){let d=await api('/appointments/');content.innerHTML=`<h3>Mis citas</h3>${d.appointments.map(apptCard).join('')||'<div class="card muted">Sin citas.</div>'}`;content.querySelectorAll('[data-video]').forEach(b=>b.onclick=()=>openVideo(+b.dataset.video))}
else if(page==='chat'){let d=await api('/conversations/');state.contacts=d.contacts;content.innerHTML=`<h3>Chats</h3>${d.contacts.map(c=>`<button class="card chat-contact" style="width:100%;text-align:left" data-id="${c.id}"><b>${c.name}</b><div class="muted">Toca para abrir conversación</div></button>`).join('')||'<div class="card muted">Aún no hay conversaciones autorizadas.</div>'}`;content.querySelectorAll('.chat-contact').forEach(b=>b.onclick=()=>openChat(+b.dataset.id,state.contacts.find(c=>c.id===+b.dataset.id).name))}
else if(page==='profile'){content.innerHTML=`<div class="card"><h3>${state.user.full_name}</h3><p class="muted">${state.user.email}</p><span class="pill">${state.user.role}</span></div><div class="card"><b>Servidor API</b><input class="search" id="apiBase" value="${state.api}"><button class="smallbtn" id="saveApi">Guardar</button></div><div class="card"><b>Biometría</b><p class="muted">Después del primer login puedes usar Face ID en iPhone o huella/biometría en Android.</p><button class="smallbtn" id="tryBio">Probar biometría</button></div><button class="primary" id="logoutApp">Cerrar sesión</button>`;$('#saveApi').onclick=saveApi;$('#tryBio').onclick=biometric;$('#logoutApp').onclick=logoutApp}
else if(page==='notifications'){let d=await api('/notifications/');content.innerHTML=`<h3>Notificaciones</h3>${d.notifications.map(n=>`<div class="card"><b>${n.title}</b><p>${n.message}</p><small>${new Date(n.created_at).toLocaleString()}</small></div>`).join('')||'<div class="card muted">Sin notificaciones.</div>'}`}
}catch(e){content.innerHTML=`<div class="card"><b>No se pudo cargar</b><p class="muted">${e.message}</p></div>`}}
function apptCard(a){return `<div class="card"><b>${a.counterpart}</b><div class="muted">${new Date(a.start_at).toLocaleString()} · ${a.modalidad||'sin modalidad'}</div><p>${a.notes||''}</p><span class="pill status">${a.status}</span>${a.video_available?`<button class="smallbtn" data-video="${a.id}" style="margin-left:8px">🎥 Videollamada</button>`:''}</div>`}
async function openChat(id,name){let d=await api('/messages/'+id+'/');content.innerHTML=`<h3>${name}</h3><div id="thread">${d.messages.map(m=>`<div class="bubble ${m.sender_id===state.user.id?'me':''}">${m.text}</div>`).join('')}</div><div class="compose"><input id="msg" placeholder="Escribe lo que sientes..."><button id="send">➤</button></div>`;$('#send').onclick=()=>sendMsg(id,name)}
async function sendMsg(id,name){let text=$('#msg').value.trim();if(!text)return;await api('/messages/'+id+'/',{method:'POST',body:JSON.stringify({text})});openChat(id,name)}
async function openVideo(id){const d=await api('/appointments/'+id+'/video/',{method:'POST',body:'{}'});alert('Sala preparada: '+d.video_call.room_key+'\nLa sala WebRTC completa está disponible desde el portal Django y puede integrarse después en una vista nativa.')}
async function saveApi(){state.api=$('#apiBase').value.replace(/\/$/,'');await prefSet('cap_api',state.api);alert('Servidor guardado')}
async function logoutApp(){try{await api('/auth/logout/',{method:'POST',body:'{}'})}catch(e){}await prefRemove('cap_token');await prefRemove('cap_user');location.reload()}

await initConfig();const t=await prefGet('cap_token'),u=await prefGet('cap_user');if(t&&u){state.token=t;state.user=JSON.parse(u);try{await api('/me/');showMain()}catch(e){}}
